[package]
name = "lego-server"
version = "0.1.0"
authors = ["Anthony Deschamps <anthony.j.deschamps@gmail.com>"]

[dependencies]
json = "0.10.2"
protobuf = "1.0.24"
read_color = "0.1.0"
try_from = "0.2.0"
ws = "0.5.3"

[build-dependencies.protobuf_build]
git = "https://github.com/plietar/rust-protobuf-build.git"
